name: Configuration Java

on:
  workflow_dispatch:

jobs:
  affichage:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v5

      - name: Lister les fichiers du runner
        run: ls -la

      - name: Configurer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Afficher la version de Java
        run: java -version

      - name: Afficher la version de Maven
        run: mvn -version